"""add username to agents, tenants and landlords

Revision ID: 25728f7d043d
Revises: 
Create Date: 2026-03-27 22:51:57.645602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25728f7d043d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('agents', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('agents', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('agents', sa.Column('role', sa.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False))
    op.drop_column('agents', 'name')
    op.add_column('landlords', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('landlords', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('landlords', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('landlords', sa.Column('role', sa.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False))
    op.drop_column('landlords', 'name')
    op.add_column('tenants', sa.Column('username', sa.String(length=100), nullable=False))
    op.add_column('tenants', sa.Column('first_name', sa.String(length=100), nullable=False))
    op.add_column('tenants', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('tenants', sa.Column('role', sa.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False))
    op.drop_column('tenants', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('tenants', 'role')
    op.drop_column('tenants', 'last_name')
    op.drop_column('tenants', 'first_name')
    op.drop_column('tenants', 'username')
    op.add_column('landlords', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('landlords', 'role')
    op.drop_column('landlords', 'last_name')
    op.drop_column('landlords', 'first_name')
    op.drop_column('landlords', 'username')
    op.add_column('agents', sa.Column('name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('agents', 'role')
    op.drop_column('agents', 'last_name')
    op.drop_column('agents', 'first_name')
    op.drop_column('agents', 'username')
    # ### end Alembic commands ###
