"""remove user-id from agents, landlords, tenants and add relationships in user

Revision ID: 4b1f297faa6c
Revises: 4beb26e115cd
Create Date: 2026-03-30 11:16:59.987229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sqla
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4b1f297faa6c'
down_revision: Union[str, Sequence[str], None] = '4beb26e115cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agents_ibfk_2'), 'agents', type_='foreignkey')
    op.drop_column('agents', 'user_id')
    op.drop_constraint(op.f('landlords_ibfk_2'), 'landlords', type_='foreignkey')
    op.drop_column('landlords', 'user_id')
    op.add_column('users', sqla.Column('landlord_id', sqla.String(length=36), nullable=True))
    op.add_column('users', sqla.Column('agent_id', sqla.String(length=36), nullable=True))
    op.create_foreign_key(None, 'users', 'landlords', ['landlord_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'agent_id')
    op.drop_column('users', 'landlord_id')
    op.add_column('landlords', sqla.Column('user_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('landlords_ibfk_2'), 'landlords', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('agents', sqla.Column('user_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('agents_ibfk_2'), 'agents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
