"""initial schema

Revision ID: 4beb26e115cd
Revises: 
Create Date: 2026-03-30 10:16:36.370576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sqla


# revision identifiers, used by Alembic.
revision: str = '4beb26e115cd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('name', sqla.String(length=100), nullable=False),
    sqla.Column('description', sqla.Text(), nullable=True),
    sqla.Column('email', sqla.String(length=30), nullable=False),
    sqla.Column('currency', sqla.Enum('KES', 'USD', 'EUR', name='currency_enum'), nullable=True),
    sqla.Column('status', sqla.Enum('ACTIVE', 'INACTIVE', name='status'), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id'),
    sqla.UniqueConstraint('name')
    )
    op.create_table('campaigns',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('title', sqla.String(length=255), nullable=True),
    sqla.Column('content', sqla.Text(), nullable=True),
    sqla.Column('status', sqla.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'PAUSED', 'EXPIRED', 'CANCELLED', name='campaignstatus'), nullable=True),
    sqla.Column('target_user_segment', sqla.String(length=255), nullable=True),
    sqla.Column('sent_at', sqla.DateTime(), nullable=True),
    sqla.Column('expires_at', sqla.DateTime(), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_table('features',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('name', sqla.String(length=100), nullable=False),
    sqla.Column('description', sqla.Text(), nullable=True),
    sqla.Column('status', sqla.Enum('ACTIVE', 'INACTIVE', name='status'), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id'),
    sqla.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('username', sqla.String(length=100), nullable=False),
    sqla.Column('first_name', sqla.String(length=100), nullable=False),
    sqla.Column('last_name', sqla.String(length=100), nullable=False),
    sqla.Column('email', sqla.String(length=50), nullable=False),
    sqla.Column('phone', sqla.String(length=20), nullable=False),
    sqla.Column('status', sqla.Enum('ACTIVE', 'INACTIVE', name='status'), nullable=True),
    sqla.Column('role', sqla.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_email'), 'tenants', ['email'], unique=True)
    op.create_table('permissions',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('name', sqla.String(length=50), nullable=True),
    sqla.Column('description', sqla.Text(), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('feature_id', sqla.String(length=36), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.Column('tenant_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id'),
    sqla.UniqueConstraint('name')
    )
    op.create_table('roles',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('name', sqla.String(length=100), nullable=True),
    sqla.Column('description', sqla.Text(), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=False),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.Column('tenant_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id'),
    sqla.UniqueConstraint('name')
    )
    op.create_table('users',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('username', sqla.String(length=100), nullable=False),
    sqla.Column('first_name', sqla.String(length=100), nullable=False),
    sqla.Column('last_name', sqla.String(length=100), nullable=False),
    sqla.Column('email', sqla.String(length=50), nullable=False),
    sqla.Column('phone', sqla.String(length=20), nullable=False),
    sqla.Column('avatar', sqla.String(length=30), nullable=True),
    sqla.Column('password', sqla.String(length=255), nullable=False),
    sqla.Column('status', sqla.Enum('ACTIVE', 'INACTIVE', name='status'), nullable=True),
    sqla.Column('role', sqla.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.Column('tenant_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('agents',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('username', sqla.String(length=100), nullable=False),
    sqla.Column('first_name', sqla.String(length=100), nullable=False),
    sqla.Column('last_name', sqla.String(length=100), nullable=False),
    sqla.Column('email', sqla.String(length=50), nullable=False),
    sqla.Column('phone', sqla.String(length=20), nullable=False),
    sqla.Column('status', sqla.Enum('ACTIVE', 'INACTIVE', name='status'), nullable=True),
    sqla.Column('role', sqla.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('user_id', sqla.String(length=36), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=True)
    op.create_table('landlords',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('username', sqla.String(length=100), nullable=False),
    sqla.Column('first_name', sqla.String(length=100), nullable=False),
    sqla.Column('last_name', sqla.String(length=100), nullable=False),
    sqla.Column('email', sqla.String(length=50), nullable=False),
    sqla.Column('phone', sqla.String(length=20), nullable=False),
    sqla.Column('status', sqla.Enum('ACTIVE', 'INACTIVE', name='status'), nullable=True),
    sqla.Column('role', sqla.Enum('TENANT', 'LANDLORD', 'AGENT', 'CUSTOMER', 'ADMIN', 'SUPER_ADMIN', 'MANAGER', name='userroles'), nullable=False),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('user_id', sqla.String(length=36), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_landlords_email'), 'landlords', ['email'], unique=True)
    op.create_table('role_permissions',
    sqla.Column('role_id', sqla.String(length=36), nullable=False),
    sqla.Column('permission_id', sqla.String(length=36), nullable=False),
    sqla.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_permissions',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('user_id', sqla.String(length=36), nullable=True),
    sqla.Column('permission_id', sqla.String(length=36), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sqla.Column('user_id', sqla.String(length=36), nullable=False),
    sqla.Column('role_id', sqla.String(length=36), nullable=False),
    sqla.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('properties',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('title', sqla.String(length=100), nullable=False),
    sqla.Column('description', sqla.Text(), nullable=True),
    sqla.Column('location', sqla.String(length=50), nullable=True),
    sqla.Column('price', sqla.Integer(), nullable=True),
    sqla.Column('bedrooms', sqla.Integer(), nullable=True),
    sqla.Column('bathrooms', sqla.Integer(), nullable=True),
    sqla.Column('images', sqla.JSON(), nullable=True),
    sqla.Column('is_available', sqla.Enum('AVAILABLE', 'UNAVAILABLE', name='housestatus'), nullable=True),
    sqla.Column('amenities', sqla.JSON(), nullable=True),
    sqla.Column('landlord_id', sqla.String(length=36), nullable=True),
    sqla.Column('agent_id', sqla.String(length=36), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('entity_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['landlord_id'], ['landlords.id'], ondelete='CASCADE'),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_location'), 'properties', ['location'], unique=False)
    op.create_index(op.f('ix_properties_price'), 'properties', ['price'], unique=False)
    op.create_table('bookings',
    sqla.Column('id', sqla.String(length=36), nullable=False),
    sqla.Column('tenant_id', sqla.String(length=36), nullable=True),
    sqla.Column('property_id', sqla.String(length=36), nullable=True),
    sqla.Column('start_date', sqla.DateTime(), nullable=True),
    sqla.Column('end_date', sqla.DateTime(), nullable=True),
    sqla.Column('total_price', sqla.Integer(), nullable=True),
    sqla.Column('status', sqla.Enum('PENDING', 'REJECTED', 'CONFIRMED', 'CANCELLED', name='bookingstatus'), nullable=True),
    sqla.Column('created_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('deleted_at', sqla.DateTime(timezone=True), nullable=True),
    sqla.Column('feature_id', sqla.String(length=36), nullable=True),
    sqla.ForeignKeyConstraint(['feature_id'], ['features.id'], ondelete='CASCADE'),
    sqla.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sqla.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sqla.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookings_total_price'), 'bookings', ['total_price'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_total_price'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_index(op.f('ix_properties_price'), table_name='properties')
    op.drop_index(op.f('ix_properties_location'), table_name='properties')
    op.drop_table('properties')
    op.drop_table('user_roles')
    op.drop_table('user_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_landlords_email'), table_name='landlords')
    op.drop_table('landlords')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_tenants_email'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('features')
    op.drop_table('campaigns')
    op.drop_table('entities')
    # ### end Alembic commands ###
