"""add audit fields to permissions

Revision ID: 6a9375e32b3c
Revises: 6a342d689b17
Create Date: 2026-05-11 13:41:49.804342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sqla
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6a9375e32b3c'
down_revision: Union[str, Sequence[str], None] = '6a342d689b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('agents', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('agents', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('agents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('agents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'agents', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'agents', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'agents', 'users', ['created_by'], ['id'])
    op.add_column('bookings', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('bookings', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('bookings', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('bookings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('bookings', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'bookings', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'bookings', 'users', ['deleted_by'], ['id'])
    op.add_column('campaigns', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('campaigns', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('campaigns', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('campaigns', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('campaigns', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'campaigns', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'campaigns', 'users', ['deleted_by'], ['id'])
    op.add_column('entities', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('entities', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('entities', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.create_foreign_key(None, 'entities', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'entities', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'entities', 'users', ['updated_by'], ['id'])
    op.add_column('features', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('features', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('features', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.create_foreign_key(None, 'features', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'features', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'features', 'users', ['deleted_by'], ['id'])
    op.add_column('landlords', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('landlords', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('landlords', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('landlords', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('landlords', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'landlords', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'landlords', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'landlords', 'users', ['updated_by'], ['id'])
    op.add_column('permissions', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('permissions', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('permissions', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.create_foreign_key(None, 'permissions', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'permissions', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'permissions', 'users', ['created_by'], ['id'])
    op.add_column('properties', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('properties', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('properties', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('properties', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('properties', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'properties', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'properties', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'properties', 'users', ['created_by'], ['id'])
    op.add_column('roles', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('roles', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('roles', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.create_foreign_key(None, 'roles', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'roles', 'users', ['updated_by'], ['id'])
    op.add_column('tenants', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('tenants', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('tenants', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('tenants', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('tenants', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'tenants', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'tenants', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'tenants', 'users', ['deleted_by'], ['id'])
    op.add_column('user_permissions', sqla.Column('updated_at', sqla.DateTime(timezone=True), nullable=False))
    op.alter_column('user_permissions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.add_column('users', sqla.Column('transporter_id', sqla.String(length=36), nullable=True))
    op.add_column('users', sqla.Column('created_by', sqla.String(length=36), nullable=True))
    op.add_column('users', sqla.Column('updated_by', sqla.String(length=36), nullable=True))
    op.add_column('users', sqla.Column('deleted_by', sqla.String(length=36), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_foreign_key(None, 'users', 'users', ['updated_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'users', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key(None, 'users', 'transporters', ['transporter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'updated_by')
    op.drop_column('users', 'created_by')
    op.drop_column('users', 'transporter_id')
    op.alter_column('user_permissions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('user_permissions', 'updated_at')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.alter_column('tenants', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('tenants', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('tenants', 'deleted_by')
    op.drop_column('tenants', 'updated_by')
    op.drop_column('tenants', 'created_by')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'deleted_by')
    op.drop_column('roles', 'updated_by')
    op.drop_column('roles', 'created_by')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.drop_constraint(None, 'properties', type_='foreignkey')
    op.alter_column('properties', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('properties', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('properties', 'deleted_by')
    op.drop_column('properties', 'updated_by')
    op.drop_column('properties', 'created_by')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'deleted_by')
    op.drop_column('permissions', 'updated_by')
    op.drop_column('permissions', 'created_by')
    op.drop_constraint(None, 'landlords', type_='foreignkey')
    op.drop_constraint(None, 'landlords', type_='foreignkey')
    op.drop_constraint(None, 'landlords', type_='foreignkey')
    op.alter_column('landlords', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('landlords', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('landlords', 'deleted_by')
    op.drop_column('landlords', 'updated_by')
    op.drop_column('landlords', 'created_by')
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_constraint(None, 'features', type_='foreignkey')
    op.drop_column('features', 'deleted_by')
    op.drop_column('features', 'updated_by')
    op.drop_column('features', 'created_by')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_constraint(None, 'entities', type_='foreignkey')
    op.drop_column('entities', 'deleted_by')
    op.drop_column('entities', 'updated_by')
    op.drop_column('entities', 'created_by')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.alter_column('campaigns', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('campaigns', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('campaigns', 'deleted_by')
    op.drop_column('campaigns', 'updated_by')
    op.drop_column('campaigns', 'created_by')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.alter_column('bookings', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('bookings', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('bookings', 'deleted_by')
    op.drop_column('bookings', 'updated_by')
    op.drop_column('bookings', 'created_by')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.drop_constraint(None, 'agents', type_='foreignkey')
    op.alter_column('agents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('agents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_column('agents', 'deleted_by')
    op.drop_column('agents', 'updated_by')
    op.drop_column('agents', 'created_by')
    # ### end Alembic commands ###
