"""add entity_id in bookings

Revision ID: 8ba9e6a4e0f8
Revises: 960db35c0710
Create Date: 2026-03-30 12:03:25.189456

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sqla
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8ba9e6a4e0f8'
down_revision: Union[str, Sequence[str], None] = '960db35c0710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sqla.Column('entity_id', sqla.String(length=36), nullable=True))
    op.create_foreign_key(None, 'bookings', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('entities_ibfk_1'), 'entities', type_='foreignkey')
    op.drop_column('entities', 'entity_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entities', sqla.Column('entity_id', mysql.VARCHAR(length=36), nullable=True))
    op.create_foreign_key(op.f('entities_ibfk_1'), 'entities', 'entities', ['entity_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'entity_id')
    # ### end Alembic commands ###
