"""update relationships in all users, agents, landlords and tenants

Revision ID: 960db35c0710
Revises: 4b1f297faa6c
Create Date: 2026-03-30 11:27:01.069909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '960db35c0710'
down_revision: Union[str, Sequence[str], None] = '4b1f297faa6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
