from enum import Enum


class PermissionEnum(str, Enum):
    VIEW_DASHBOARD = "view_dashboard"
    VIEW_REPORTS = "view_reports"
    GENERATE_DESCRIPTION = "generate_description"
    VIEW_PROPERTIES = "view_properties"
    VIEW_PROPERTY = "view_property"
    VIEW_BOOKINGS = "view_bookings"
    VIEW_BOOKING = "view_booking"
    CREATE_BOOKING = "create_booking"
    UPDATE_BOOKING = "update_booking"
    DELETE_BOOKING = "delete_booking"
    VIEW_USER = "view_user"
    CREATE_USER = "create_user"
    UPDATE_USER = "update_user"
    DELETE_USER = "delete_user"
    VIEW_CAMPAIGNS = "view_campaigns"
    VIEW_CAMPAIGN = "view_campaign"
    MANAGE_PROPERTIES = "manage_properties"
    MANAGE_BOOKINGS = "manage_bookings"
    MANAGE_USERS = "manage_users"
    MANAGE_CAMPAIGNS = "manage_campaigns"
    MANAGE_TENANTS = "manage_tenants"
    MANAGE_LANDLORDS = "manage_landlords"
    MANAGE_AGENTS = "manage_agents"
    MANAGE_MOVERS = "manage_movers"
    MANAGE_DISCOUNTS = "manage_discounts"
    MANAGE_PROMOTIONS = "manage_promotions"
    MANAGE_CONTENT = "manage_content"
    MANAGE_SETTINGS = "manage_settings"